### ISSUE TITLE
Feature: Allow integration of other modules.

### ISSUE THREAD

**Issue by juacas** [moodleou/moodle-report_editdates#17]
It would be very handy to allow other modules to provide the class that extends report_editdates_mod_date_extractor in their own directories.

It seems to be easy to implement by checking folder:
 $filename = $CFG->dirroot . '/mod/' . $modname . '/classes/editdates.php';
in addition to: 
 $filename = $CFG->dirroot . '/report/editdates/mod/' . $modname . 'dates.php';

I've implemented the idea and it works flawlessly.

**Comment by timhunt** [comment]
I have now done an implementation of this, doing what I suggested in pull request #18.
