### ISSUE TITLE
Slow page load

### ISSUE THREAD

**Issue by mltoh** [moodleou/moodle-report_editdates#23]
Instructors at my college really love this function but noticed that ever since the version 2.7 upgrade (on Moodle 3.5), the page loads really slowly (minutes to load) and is most apparent when a course contains a lot of content (which course contain labels, assignments, discussions, quizzes). 

Some browsers handle the slowness better than others as expected. However, Firefox seem to perform the worst where it spits the error "a web page is slowing down your browser." The slow page load does not seem to be apparent on courses with minimal content. I'm wondering if the issue is linked to the new "restricted date access" as I did not notice that in the version prior.

**Comment by timhunt** [comment]
I don't know why it is so slow. I don't know what changed. That needs to be investigated. However, it will relate to things that are on the page.

**Comment by krajewsk** [comment]
We also recently updated to 2.7 and at first found the report dieing on large activity classes (out of memory error). We had to bump up the PHP memory allocation on that page from the site default of 128MB to 512MB to get it to load.  The page is pretty slow to interact with once loaded.

**Comment by sbourget** [comment]
I've gotten a few reports of this as well, I haven't had a chance to dig into it too deeply, but I think it may be based on the number of date-pickers that are loaded on the page.  Previous versions only loaded the dates for a single module type at a time. The new version (2.7) loads all of the activity modules.  On some courses this means we are now loading over 300 date pickers on a single page.

I found I can effectively recreate the slow page warning by creating a course (using the moodle make test course for size S) turning on completion tracking for the course, and then duplicating the assignment module instances so I have around 30.  Visiting the dates report will flash a slow page warning.

Note: a size M test course will generate a memory exhaustion error if completion tracking is enabled. and the memory is set to 128MB

**Comment by timhunt** [comment]
Date-picker JavaScript is a good guess. Not sure what, if anything, we could do to work-around it.

**Comment by jprovasnik** [comment]
My Teachers love this report. Unfortunately, with 100 activities in a course, the page times out or never fully loads. Anyway to not have all activities load on the initial load would be helpful.

**Comment by timhunt** [comment]
I am just testing on a course with 82 activities, and it is working OK (in Firefox and Chrome). It is painfully slow in Edge and IE. You may have to advise your users to use a better browser.

The code that is slow is standard Moodle forms, so there is not much we can do in this plugin.
