### ISSUE TITLE
due date time to 1 minute intervals [ new enhancement ]

### ISSUE THREAD

**Issue by dipakburnwal** [moodleou/moodle-report_editdates#25]
Hi Tim,
First of all thanks for such a great tool. However I have a request regarding this tool that whether it is possible to make the assignment due date time to 1 minute intervals rather than 5.
I am running Moodle 3.6
Thanks, again

**Comment by timhunt** [comment]
Thanks. Moodle core changed this in Moodle 3.5 (https://tracker.moodle.org/browse/MDL-60682), but we forgot to update this plugin. Fixed now.
