### ISSUE TITLE
Recurrent activity dates and new courses

### ISSUE THREAD

**Issue by garciagregorio** [moodleou/moodle-report_editdates#32]
Hello, I'm kind of new in the Moodle world.

Now I'm working with some courses, one I've created has a lot of activities, forums, tasks, exams, all of them with specific date of completion.

I want to backup this one, and restoring it several times, at differente dates, but the date and times of the activities are the same of the original one... I mean the same dates and time from the backup.

My course is weekly format... is there a way to automatically change the date and times of the activities??, I don't want to change every activity, exam or whatever everytime I restore the course.

**Comment by timhunt** [comment]
Please ask this question in the Moodle forums. It is not really relevant to this plugin.
