### ISSUE TITLE
What should the report_editdates timelinemax setting be?

### ISSUE THREAD

**Issue by dave559** [moodleou/moodle-report_editdates#33]
Apologies for asking this as an 'issue', I have asked on the Moodle forums but without any replies as yet.

I am trying to make a test copy of our Moodle site so as to be able to safely test before a major upgrade.

I have managed to copy the site, data, and DB successfully, but now, when logged in as an admin, I am presented with the following message from the editdates plugin, which I do not recall seeing before:

> The settings shown below were added during your last Moodle upgrade. Make any changes necessary to the defaults and then click the 'Save changes' button at the bottom of this page.
> 
> New settings - Dates
> timelinemax
> report_editdates | timelinemax
> Default: 3
> 
> timelinemaxdesc

I have had a look at the editdates site and repo, but can't see anything that explains this setting.

Is there a way that I can check what this setting is on the original site (I have tried searching all the above keywords in the administration area, with no luck), or what the setting values actually mean or should be (I can't find any documentation about this)?

(I suspect that accepting the default would probably be fine, but want to be sure.)

**Comment by timhunt** [comment]
Don't konw why this is happening. It is a core issue (in the config settings code). Anyway, default is fine.
