### ISSUE TITLE
Forum dates

### ISSUE THREAD

**Issue by Syxton** [moodleou/moodle-report_editdates#34]
Sometimes you get a "From" and  "To" or "Expect completed on"  You would expect to see "Due date" & "Cut-off" dates.  Seen in Moodle 3.7 and 3.9

**Comment by timhunt** [comment]
Thanks for fixing this, and sorry it took me so long to review the fix.

**Comment by mgancarzdsi** [comment]
Hi @timhunt , I think this change might have broken the use of this plugin on Moodle 3.5.  With the latest version 2.9 installed, I get the errors below in a course with Forum activities on Moodle 3.5.15+ (Build: 20201224), when going to /report/editdates/index.php?id=courseid

> Invalid get_string() identifier: 'duedate' or component 'forum'. Perhaps you are missing $string['duedate'] = ''; in mod/forum/lang/en/forum.php?
> line 349 of /lib/classes/string_manager_standard.php: call to debugging()
> line 7191 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
> line 33 of /report/editdates/mod/forumdates.php: call to get_string()
> line 190 of /report/editdates/form.php: call to report_editdates_mod_forum_date_extractor->get_settings()
> line 204 of /lib/formslib.php: call to report_editdates_form->definition()
> line 81 of /report/editdates/index.php: call to moodleform->__construct()
> 
> Notice: Undefined property: stdClass::$duedate in /var/www/html/sitenameremoved/report/editdates/mod/forumdates.php on line 34
> Invalid get_string() identifier: 'cutoffdate' or component 'forum'. Perhaps you are missing $string['cutoffdate'] = ''; in mod/forum/lang/en/forum.php?
> line 349 of /lib/classes/string_manager_standard.php: call to debugging()
> line 7191 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
> line 37 of /report/editdates/mod/forumdates.php: call to get_string()
> line 190 of /report/editdates/form.php: call to report_editdates_mod_forum_date_extractor->get_settings()
> line 204 of /lib/formslib.php: call to report_editdates_form->definition()
> line 81 of /report/editdates/index.php: call to moodleform->__construct()
> 
> Notice: Undefined property: stdClass::$cutoffdate in /var/www/html/sitenameremoved/report/editdates/mod/forumdates.php on line 38
> Invalid get_string() identifier: 'duedate' or component 'forum'. Perhaps you are missing $string['duedate'] = ''; in mod/forum/lang/en/forum.php?
> line 349 of /lib/classes/string_manager_standard.php: call to debugging()
> line 7191 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
> line 33 of /report/editdates/mod/forumdates.php: call to get_string()
> line 190 of /report/editdates/form.php: call to report_editdates_mod_forum_date_extractor->get_settings()
> line 204 of /lib/formslib.php: call to report_editdates_form->definition()
> line 81 of /report/editdates/index.php: call to moodleform->__construct()

**Comment by timhunt** [comment]
Should have realised this this change, to fix the report for a change in Moodle core in 3.7, would break compatibility with older versions.

If you want to keep using Moodle 3.5, you will need to downgrade this report back to the previous version. Sorry.

**Comment by mgancarzdsi** [comment]
Thank you Tim, I reverted to the previous version for the deployment and have it working. Can't figure out how to downgrade it in my staging environment, but that's okay, that database needs a refresh anyways.

I don't know if there's a way to change the name of the version in the plugin database? It's called "Version 2.9 for Moodle 3.5+" though I do see only 3.7 and later in the actual version list on: https://moodle.org/plugins/pluginversion.php?id=23127

I might have downloaded it based on the "for Moodle 3.5+" name without actually noticing that 3.5 and 3.6 are not listed in the supported versions, I should be more careful.

**Comment by timhunt** [comment]
Oops! thanks. I updated the moodle version compatibility info in response to your report, but not the name. Done now.
